# Generated by Django 5.2.1 on 2025-05-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('date_of_joining', models.DateField()),
            ],
        ),
    ]
